### ISSUE TITLE
Ajustar backend carrito.php

### ISSUE THREAD

**Issue by CarlosMaita** [RouxaVzla/Rouxa#13]
(1) construir lista de productos
(2) codificar resumen
(3) Colocar funcional el boton de "Serguir comprando"

**Comment by alexis9261** [comment]
Tareas:
1. Colocar funcional el Boton "Editar"
  1.1 Actualizar el articulo. En Session.
2. Colocar funcional el Boton "Eliminar"
3. Mostrar Imagen del Modelo
4. Mostrar los colores que corresponden al modelo.
5. Calculo del IVA
