### ISSUE TITLE
Modificacion de la pagina de compras

### ISSUE THREAD

**Issue by alexis9261** [RouxaVzla/Rouxa#5]
Hombre ya modifique la parte de compras, el Front end.

Revisa y me dices, lo monte directo al Master. Y no hice pull request

Alli me equivoque en esa.. Pero no modifique nada pues..
Tal vez, lo q haya q modificar otra vez, es la parte de agregar un producto, por el cambio q se hizo en el hash.

**Comment by CarlosMaita** [comment]
Fino!
